### ISSUE TITLE
Randomly getting RangeError

### ISSUE THREAD

**Issue by techno-disaster** [tal-tech/flutter_intro#22]
This can be reproduced in the example app, might not come at the first time but does after a couple of tries if you try skipping through the intro very fast.
Stack: 
```
I/flutter (23393): start

══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following RangeError was thrown building
_OverlayEntryWidget-[LabeledGlobalKey<_OverlayEntryWidgetState>#54929](dirty, dependencies:
[MediaQuery], state: _OverlayEntryWidgetState#760eb):
RangeError (index): Invalid value: Not in inclusive range 0..3: 4

When the exception was thrown, this was the stack:
#0      List.[] (dart:core-patch/growable_array.dart:254:60)
#1      Intro._showOverlay.<anonymous closure> (package:flutter_intro/flutter_intro.dart:230:57)
#2      _OverlayEntryWidgetState.build (package:flutter/src/widgets/overlay.dart:208:34)
#3      StatefulElement.build (package:flutter/src/widgets/framework.dart:4713:27)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4596:15)
#5      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4769:11)
#6      Element.rebuild (package:flutter/src/widgets/framework.dart:4286:5)
#7      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2583:33)
#8      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:878:21)
#9      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:328:5)
#10     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1147:15)
#11     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1084:9)
#12     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1000:5)
#16     _invoke (dart:ui/hooks.dart:163:10)
#17     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:259:5)
#18     _drawFrame (dart:ui/hooks.dart:126:31)
(elided 3 frames from dart:async)

════════════════════════════════════════════════════════════════════════════════════════════════════
E/flutter (23393): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: setState() called after dispose(): _DelayRenderedWidgetState#e84a4(lifecycle state: defunct, not mounted)
E/flutter (23393): This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.
E/flutter (23393): The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
E/flutter (23393): This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().
E/flutter (23393): #0      State.setState.<anonymous closure> (package:flutter/src/widgets/framework.dart:1052:9)
E/flutter (23393): #1      State.setState (package:flutter/src/widgets/framework.dart:1087:6)
E/flutter (23393): #2      _DelayRenderedWidgetState.didUpdateWidget.<anonymous closure> (package:flutter_intro/delay_rendered_widget.dart:81:13)
E/flutter (23393): #3      _rootRun (dart:async/zone.dart:1420:47)
E/flutter (23393): #4      _CustomZone.run (dart:async/zone.dart:1328:19)
E/flutter (23393): #5      _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
E/flutter (23393): #6      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
E/flutter (23393): #7      _rootRun (dart:async/zone.dart:1428:13)
E/flutter (23393): #8      _CustomZone.run (dart:async/zone.dart:1328:19)
E/flutter (23393): #9      _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1260:23)
E/flutter (23393): #10     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
E/flutter (23393): #11     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:395:19)
E/flutter (23393): #12     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:426:5)
E/flutter (23393): #13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
E/flutter (23393): 
```

**Comment by hellohejinyu** [comment]
Thanks :)
